### ISSUE TITLE
Почему?

### ISSUE THREAD

**Issue by TheDigitalCat** [va-utils/WhereIsMyPhoto#1]
360 обнаружил, что загруженный файл содержит троян, который может проникнуть в систему и воровать пароли, фотографии и личную информацию

Файл трояна: WhereIsMyPhotoSetup-0.6.exe

Risks: Троян (HEUR/QVM20.1.F745.Malware.Gen)

**Comment by va-utils** [comment]
Возможно, антивирусу не нравится установщик (Nullsoft Scriptable Install System)
https://www.virustotal.com/#/file/f396a564bd4bb749d95993f4d2add6e120e6ad37d02e69213603016b3601c616/detection
https://www.virustotal.com/#/file/dfb01b114d345b867a52963fcd3f3477eb5b2a9cfd8ff6b1d125e23971962096/detection
Чем им не нравится установщик не знаю, но NSIS существует очень многие годы и я давно им пользуюсь, мне кажется ему можно доверять и это ложное срабатывание.

**Comment by TheDigitalCat** [comment]
На собранный из исходников не ругается.
